# Generated by Django 5.2.5 on 2025-09-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('purpose', models.CharField(choices=[('Похудение', 'Похудение'), ('Набор мышечной массы', 'Набор мышечной массы'), ('Поддержание формы', 'Поддержание формы'), ('Реабилитация после травм', 'Реабилитация после травм'), ('Подготовка к соревнованиям', 'Подготовка к соревнованиям')], max_length=30, verbose_name='Цель посещения')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
        ),
    ]
